- hosts: frontends
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      #  url: "http://frontend1.{{ GUID }}.example.opentlc.com/ping"
      url: "http://localhost/ping"
      return_content: yes
    until: '"alive" in result.content'
    retries: 10
    delay: 1
    register: result
