---
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item }}"
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: apps
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=apps, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  copy:
     src: /root/.ssh/openstack.pem
     dest: /tmp/openstack.pem
  loop:
     - app1
     - app2

- name: Create instances
  os_server:
    cloud: openstack
    name: appdb1
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: db
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=appdbs, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  copy:
     src: /root/.ssh/openstack.pem
     dest: /tmp/openstack.pem

- name: Create instances
  os_server:
    cloud: openstack
    name: frontend
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: frontend
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=frontends, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  copy:
     src: /root/.ssh/openstack.pem
     dest: /tmp/openstack.pem

- name: Add floating IP to instances
  os_floating_ip:
    cloud: openstack
    state: "{{ openstack_server_state | default('present') }}"
    reuse: yes
    server: "{{ item  }}"
    network: ext_network
    wait: true
    timeout: 180
  loop:
     - app1
     - app2
     - appdb1
     - frontend

# tasks file for osp.servers
