---
- name: Create instances
  os_server:
    cloud: openstack
    name: "{{ item }}"
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: apps
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=apps, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd >> /home/cloud-user/.ssh/authorized_keys
  loop:
     - app1
     - app2

- name: Create instances
  os_server:
    cloud: openstack
    name: appdb1
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: db
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=appdbs, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd >> /home/cloud-user/.ssh/authorized_keys

- name: Create instances
  os_server:
    cloud: openstack
    name: frontend
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_groups: frontend
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group=frontends, deployment_name=QA"
    userdata: |
      #!/bin/bash
      cat ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd >> /home/cloud-user/.ssh/authorized_keys

- name: Add floating IP to instances
  os_floating_ip:
    cloud: openstack
    state: "{{ openstack_server_state | default('present') }}"
    reuse: yes
    server: "{{ item  }}"
    network: ext_network
    wait: true
    timeout: 180
  loop:
     - app1
     - app2
     - appdb1
     - frontend

# tasks file for osp.servers
