---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- rpm_key:
    state: present
    key: https://www.opentlc.com/download/ansible_bootcamp/repo/RPM-GPG-KEY-PGDG-96

- name: enable repos
  yum_repository:
    name: rhel-7-server-rh-common-rpms
    description: EPEL YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-rh-common-rpms
- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: rhel-8-for-x86_64-appstream-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/rhel-8-for-x86_64-appstream-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: rhel-8-for-x86_64-baseos-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/rhel-8-for-x86_64-baseos-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/3)
  yum_repository:
    name: rhel-8-for-x86_64-highavailability-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/rhel-8-for-x86_64-highavailability-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/4)
  yum_repository:
    name: openstack-16-for-rhel-8-x86_64-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/openstack-16-for-rhel-8-x86_64-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/5)
  yum_repository:
    name: fast-datapath-for-rhel-8-x86_64-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/fast-datapath-for-rhel-8-x86_64-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/6)
  yum_repository:
    name: ansible-2.8-for-rhel-8-x86_64-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://192.0.2.253/repos/ansible-2.8-for-rhel-8-x86_64-rpms
    gpgcheck: no
    enabled: 1

