---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- rpm_key:
    state: present
    key: https://www.opentlc.com/download/ansible_bootcamp/repo/RPM-GPG-KEY-PGDG-96

- name: enable repos
  yum_repository:
    name: rhel-7-server-rh-common-rpms
    description: EPEL YUM repo
    baseurl: http://d3s3zqyaz8cp2d.cloudfront.net/repos/tower/3.7.0-4/rhel-7-server-rh-common-rpms
- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: rhel-7-server-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: rhel-7-server-rh-common-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-rh-common-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/3)
  yum_repository:
    name: rhel-7-server-extras-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-extras-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/4)
  yum_repository:
    name: rhel-7-server-optional-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-7-server-optional-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/5)
  yum_repository:
    name: rhel-server-rhscl-7-rpms
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.5.3-1/rhel-server-rhscl-7-rpms
    gpgcheck: no
    enabled: 1
- name: Add multiple repositories into the same file (1/6)
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    mirrorlist: http://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    gpgcheck: no
    enabled: 1

